"""
端口/适配器接口定义 — Application 层只依赖这些接口，不依赖具体实现。
"""

from abc import ABC, abstractmethod
from typing import Optional
from .models import Account, Credential, SignSchedule, TaskResult, BindingInfo


class AccountRepository(ABC):
    @abstractmethod
    async def find_by_id(self, account_id: str) -> Optional[Account]: ...
    @abstractmethod
    async def save(self, account: Account) -> None: ...
    @abstractmethod
    async def delete(self, account_id: str) -> bool: ...
    @abstractmethod
    async def find_all(self) -> list[Account]: ...

class SignScheduleRepository(ABC):
    @abstractmethod
    async def find_by_account(self, account_id: str) -> Optional[SignSchedule]: ...
    @abstractmethod
    async def save(self, schedule: SignSchedule) -> None: ...
    @abstractmethod
    async def delete(self, account_id: str) -> bool: ...
    @abstractmethod
    async def find_overdue(self, current_time: str) -> list[SignSchedule]: ...
    @abstractmethod
    async def find_all(self) -> list[SignSchedule]: ...

class CredentialCache(ABC):
    @abstractmethod
    async def get(self, token_hash: str) -> Optional[Credential]: ...
    @abstractmethod
    async def set(self, token_hash: str, credential: Credential, ttl_seconds: int) -> None: ...
    @abstractmethod
    async def invalidate(self, token_hash: str) -> None: ...

class SkylandApiPort(ABC):
    @abstractmethod
    async def get_grant_code(self, token: str) -> str: ...
    @abstractmethod
    async def get_cred_by_code(self, grant_code: str) -> Credential: ...
    @abstractmethod
    async def get_cred_by_token(self, token: str) -> Credential: ...
    @abstractmethod
    async def get_binding_list(self, sign_token: str, cred: str) -> list[BindingInfo]: ...
    @abstractmethod
    async def do_sign(self, sign_token: str, cred: str) -> list[dict]: ...
    @abstractmethod
    async def refresh_token(self, old_token: str, cred: str) -> str: ...
    @abstractmethod
    async def verify_token(self, token: str) -> tuple[bool, str, Optional[Credential]]: ...
    @abstractmethod
    async def send_login_code(self, phone: str) -> dict: ...
    @abstractmethod
    async def login_by_phone_code(self, phone: str, code: str) -> dict: ...

class NotificationPort(ABC):
    @abstractmethod
    async def send(self, account_id: str, message: str) -> bool: ...
    @abstractmethod
    async def broadcast(self, message: str, account_ids: list[str]) -> int: ...

class DeviceFingerprintPort(ABC):
    @abstractmethod
    async def get_did(self, force_refresh: bool = False) -> str: ...
